# 站点配置
site_name: Dwj's Wiki
site_url: https://wiki.dwj601.cn/
repo_url: https://github.com/Explorer-Dong/explorer-dong.github.io
repo_name: explorer-dong.github.io
edit_uri: edit/main/docs/


# 主题配置
theme:
  name: material
  language: zh
  custom_dir: overrides
  # 图标
  logo: https://dwj-oss.oss-cn-nanjing.aliyuncs.com/web-imgs/img-static/wiki-16px.svg
  favicon: https://dwj-oss.oss-cn-nanjing.aliyuncs.com/web-imgs/img-static/wiki-16px.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  # 颜色
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: 暗色模式
    - scheme: slate
      primary: black  # 控件颜色
      toggle:
        icon: material/brightness-4
        name: 亮色模式
  features:
    - navigation.tabs
    # - navigation.tabs.sticky       # 固定导航栏
    # - navigation.path              # 显示当前页面路径（有问题）
    # - navigation.sections          # 分类页小标题
    # - navigation.expand            # 分类页默认展开（一般与 navigation.sections 一起使用）
    - navigation.indexes           # 不显示分类索引首页
    - navigation.top               # 顶部导航栏
    - navigation.instant           # 导航栏即时更新
    - navigation.instant.prefetch  # 预加载
    - navigation.instant.progress  # 进度条
    - navigation.footer            # 页脚
    - content.code.copy            # 代码块复制按钮
    - content.code.select          # 代码块选中行
    - content.tooltips             # 内容悬浮提示
    - content.action.edit          # 编辑源文件按钮
    - content.action.view          # 查看源文件按钮
    - search.highlight             # 搜索结果高亮
    - search.share                 # 社交分享按钮
    - search.suggest               # 搜索建议
    - toc.follow                   # 目录跟随滚动（需要 markdown_extensions.toc.permalink 开启）
    - header.autohide              # 自动隐藏顶部导航栏
    - announce.dismiss             # 支持手动关闭公告


# md 语法扩展
markdown_extensions:
  # 并列嵌套（需要和 superfences 一起使用）
  - pymdownx.tabbed:
      alternate_style: true
  # 悬浮提示
  - abbr
  - attr_list
  - pymdownx.snippets
  # 折叠块
  - pymdownx.details
  # 脚注
  - footnotes
  # 目录
  - toc:
      permalink: true             # 显示标题链接
      toc_depth: 4                # 显示目录深度
      title: 文章目录             # 目录标题
      permalink_title: 页面定位   # 链接标题
  # 数学公式
  - pymdownx.arithmatex:
      generic: true
  # 表情符号
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 图片标题（需要引入额外的语法）
  - pymdownx.blocks.caption
  # 代码高亮
  - pymdownx.highlight:
      # auto_title: true           # 自动标题
      use_pygments: true         # 第三方库增强
      pygments_lang_class: true  # 语言定制化高亮
      linenums: true             # 显示行号
      anchor_linenums: true      # 行号锚点
      line_spans: __span         # 行号容器（移动端适配）
  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true


# 注入
extra_javascript:
  # 数学公式（MathJax）
  - injects/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # 数学公式（KaTeX）
  # - injects/javascripts/katex.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  # 数学公式（KaTeX）
  # - https://unpkg.com/katex@0/dist/katex.min.css


# 插件配置
plugins:
#   # 搜索功能
#   - search
#   # 显示文章创建和修改时间
#   - git-revision-date-localized:
#       enable_creation_date: true
#       type: date
#   # 显示文章作者
#   - git-authors
#   # 图片可点击放大
#   - glightbox


# 页面导航
nav:
  - index.md
  - 绩点: 
    - GPA/index.md
    - 1st-term:
      - GPA/1st-term/AdvancedMath.md
    - 2nd-term:
      - GPA/2nd-term/ObjectOrientedProgramming.md
    - 3rd-term:
      - GPA/3rd-term/CollegePhysics_2.md
      - GPA/3rd-term/DS&Algo.md
      - GPA/3rd-term/DigitalLogicCircuit.md
      - GPA/3rd-term/LinearAlgebra.md
    - 4th-term:
      - GPA/4th-term/MachineLearning.md
      - GPA/4th-term/OptMethod.md
      - GPA/4th-term/ProbAndStat.md
      - GPA/4th-term/PyAlgo.md
      - GPA/4th-term/PyApply.md
      - GPA/4th-term/SysBasic.md
    - 5th-term:
      - GPA/5th-term/ComputerOrganization.md
      - GPA/5th-term/DataBase.md
      - GPA/5th-term/DataMining.md
      - GPA/5th-term/DeepLearning.md
      - GPA/5th-term/DigitalImageProcessing.md
      - GPA/5th-term/OperatingSystem.md
    - 6th-term:
      - GPA/6th-term/ComputerNetwork.md
      - GPA/6th-term/ComputerVision.md
      - GPA/6th-term/NaturalLanguageProcessing.md
      - GPA/6th-term/SmartEducation.md
      - GPA/6th-term/SpeechRecognition.md
  - 炼丹:
    - DataScience/index.md
    - DataScience/matplotlib-tutorial.md
    - DataScience/numpy-tutorial.md
  - 算法:
    - Algorithm/index.md
    - Algorithm/templates.md
    - Algorithm/basic-algo.md
    - Algorithm/basic-ds.md
    - Algorithm/advanced-algo.md
    - Algorithm/advanced-ds.md
  - 前端:
    - FrontEnd/index.md
    - HTML:
      - FrontEnd/HTML/html-basic.md
    - CSS:
      - FrontEnd/CSS/css-basic.md
    - JavaScript:
      - FrontEnd/JavaScript/javascript-basic.md
    - Hexo:
      - FrontEnd/Hexo/build-your-own-website-with-hexo.md
      - FrontEnd/Hexo/hexo-deployment.md
      - FrontEnd/Hexo/hexo-enhancement.md
  - 后端:
    - BackEnd/index.md
    - C++:
      - BackEnd/CPlusPlus/cpp-basic.md
      - Crow:
        - BackEnd/CPlusPlus/Crow/crow-tutorial.md
    - Python:
      - BackEnd/Python/python-basic.md
      - Flask:
        - BackEnd/Python/Flask/deploy-flask.md
  - 数据库:
    - DataBase/index.md
    - ElasticSearch:
      - DataBase/ElasticSearch/elastic-search-basic.md
    - MySQL:
      - DataBase/MySQL/mysql-basic.md
      - DataBase/MySQL/solve-mysql-problems.md
    - Redis:
      - DataBase/Redis/redis-basic.md
    - openGauss:
      - DataBase/openGauss/opengauss-basic.md
      - DataBase/openGauss/opengauss-import-data.md
      - DataBase/openGauss/opengauss-remote-connect.md
  - 运维:
    - Operation/index.md
    - Nginx:
      - Operation/Nginx/nginx-basic.md
      - Operation/Nginx/nginx-command.md
      - Operation/Nginx/solve-nginx-reload-error.md
      - Operation/Nginx/whereis-nginx.md
    - Safe:
      - Operation/Safe/solve-server-invade.md
    - Shell:
      - Operation/Shell/shell-basic.md
      - Operation/Shell/solve-shell-problems.md
      - Operation/Shell/ubuntu-guide.md
  - 工具:
    - DevTools/index.md
    - DevTools/jetbrains-license.md
    - CLion:
      - DevTools/CLion/config-clion.md
      - DevTools/CLion/solve-clion-cannot-open-relative-file.md
      - DevTools/CLion/solve-clion-decoding-error.md
    - DevCpp:
      - DevTools/DevCpp/devc-self-config.md
    - Git:
      - DevTools/Git/git-basic.md
      - DevTools/Git/git-pull-request.md
      - DevTools/Git/git-self-define-command.md
      - DevTools/Git/solve-git-problems.md
    - IDLE:
      - DevTools/IDLE/idle-self-config.md
  - 博客: https://blog.dwj601.cn/


# 社交链接
extra:
  analytics:
    provider: google
    property: G-56NDVC0D5B
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Explorer-Dong
      name: GitHub
    - icon: fontawesome/solid/c
      link: https://blog.csdn.net/qq_73408594
      name: CSDN


# 页脚 Copyright
copyright: Copyright &copy; 2024 - 2025 Wenjie
