# ==================== 站点配置 ====================
site_name: 开放知识社群
site_url: https://wiki.dwj601.cn/
repo_url: https://github.com/Explorer-Dong/wiki
repo_name: Open Wiki Community
edit_uri: edit/main/docs/


# ==================== 主题配置 ====================
theme:
  name: material
  language: zh
  custom_dir: overrides
  # 图标
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  # 颜色
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到自动模式
  features:
    # - header.autohide              # 自动隐藏页面头部
    - navigation.tabs                # 顶部一级分类导航栏
    # - navigation.tabs.sticky         # 固定顶部一级分类导航栏
    - navigation.sections          # 分类页小标题
    # - navigation.expand            # 分类页默认展开
    - navigation.indexes           # 不显示分类索引首页
    - navigation.top               # 顶部导航栏
    - navigation.footer            # 页脚
    - content.code.copy            # 代码块复制按钮
    - content.code.select          # 代码块选中行
    - content.tooltips             # 内容悬浮提示
    - content.action.edit          # 编辑源文件按钮
    - content.action.view          # 查看源文件按钮
    - search.highlight             # 搜索结果高亮
    - search.share                 # 社交分享按钮
    - search.suggest               # 搜索建议
    - toc.follow                   # 目录跟随滚动（需要 markdown_extensions.toc.permalink 开启）
    - announce.dismiss             # 支持手动关闭公告


# ==================== 语法扩展 ====================
markdown_extensions:
  # 并列嵌套（需要和 superfences 一起使用）
  - pymdownx.tabbed:
      alternate_style: true
  # 悬浮提示
  - abbr
  - attr_list
  - pymdownx.snippets
  # 折叠块
  - pymdownx.details
  # 内容框
  - admonition
  # 脚注
  - footnotes
  # 目录
  - toc:
      # permalink: true             # 显示标题链接
      toc_depth: 3                # 显示目录深度
      title: 本页目录                 # 目录标题
      permalink_title: 页面定位   # 链接标题
      slugify: !!python/name:pymdownx.slugs.uslugify  # 禁止重写标题，借鉴 oi-wiki 的配置
  # 数学公式
  - pymdownx.arithmatex:
      generic: true
  # 表情符号
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 代码高亮
  - pymdownx.highlight:
      # auto_title: true           # 自动标题
      use_pygments: true         # 第三方库增强
      pygments_lang_class: true  # 语言定制化高亮
      linenums: true             # 显示行号
      anchor_linenums: true      # 行号锚点
      line_spans: __span         # 行号容器（移动端适配）
  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true


# ==================== 样式注入 ====================
extra_javascript:
  # KaTeX
  - javascripts/katex.js
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.js
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/contrib/auto-render.min.js
  # mermaid
  - https://cdn.dwj601.cn/cdn-js/mermaid/mermaid.min.js
  # 外链跳转
  - javascripts/link_blank.js
  # 百度统计
  - javascripts/baidu_tongji.js
  # 解析图片的 alt 属性
  - javascripts/show_img_alt.js
  # 首页脚本（暂时不用，会出现屏幕闪烁的情况）
  # - javascripts/homepage.js
  # 聊天机器人（暂时不用，后期有机会自己部署到国内服务器）
  # - javascripts/robot.js
extra_css:
  # KaTeX
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.css
  # 自定义样式
  - stylesheets/extra.css


# ==================== 插件配置 ====================
plugins:
  # 搜索功能
  - search:
      lang: zh
  # 显示文章创建和修改时间
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
      timezone: Asia/Shanghai
  # 显示文章作者（头像与 GitHub Profile 链接）
  - git-committers:
      repository: Explorer-Dong/wiki
      branch: main
  # 图片可点击放大
  - glightbox:
      auto_caption: false
  # meta 配置
  - meta


# ==================== 额外配置 ====================
extra:
  # 谷歌分析
  analytics:
    provider: google
    property: G-56NDVC0D5B
  # 文章状态定义
  status:
    new: 待更新
    deprecated: 即将废弃
  # 页面底部社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Explorer-Dong
      name: GitHub
    - icon: fontawesome/solid/c
      link: https://blog.csdn.net/qq_73408594
      name: CSDN


# ==================== 文章权限 ====================
copyright: <a href="https://beian.miit.gov.cn/">苏ICP备2024087610号-1</a>


# ==================== 页面导航 ====================
nav:
  - index.md
  - 基础:
    - base/index.md
    - 人工智能基础:
      - 数字图像处理:
        - base/ai/digital-image-processing/index.md
      - 语音信号处理:
        - base/ai/speech-signal-processing/index.md
      - 机器学习:
        - base/ai/machine-learning/index.md
        - base/ai/machine-learning/data.md
        - base/ai/machine-learning/eval.md
        - 模型:
          - base/ai/machine-learning/model/index.md
          - base/ai/machine-learning/model/linear-model.md
          - base/ai/machine-learning/model/decision-tree-model.md
          - base/ai/machine-learning/model/bayes-model.md
          - base/ai/machine-learning/model/probability-graph-model.md
          - base/ai/machine-learning/model/ensemble-learning.md
          - base/ai/machine-learning/model/lazy-learning.md
          - base/ai/machine-learning/model/cluster-learning.md
          - base/ai/machine-learning/model/semi-supervised-learning.md
      - 深度学习:
        - base/ai/deep-learning/index.md
      - 数据挖掘:
        - base/ai/data-mining/index.md
        - base/ai/data-mining/data-preprocess.md
        - base/ai/data-mining/association-analysis.md
        - base/ai/data-mining/anomaly-detection.md
      - 自然语言处理:
        - base/ai/natural-language-processing/index.md
        - base/ai/natural-language-processing/word-embedding.md
        - base/ai/natural-language-processing/sequence-classification.md
        - base/ai/natural-language-processing/sequence-generation.md
        - base/ai/natural-language-processing/pre-training.md
      - 计算机视觉:
        - base/ai/computer-vision/index.md
        - base/ai/computer-vision/image-classification.md
        - base/ai/computer-vision/object-detection.md
        - base/ai/computer-vision/image-super-resolution.md
        - base/ai/computer-vision/action-recognition.md
      - 智慧教育:
        - base/ai/intelligent-education/index.md
    - 计算机基础:
      - 面向对象程序设计:
        - base/cs/object-oriented-programming/index.md
      - 数字逻辑电路:
        - base/cs/digital-logic-circuit/index.md
      - 计算机系统基础:
        - base/cs/computer-system-basic/index.md
      - 数据库:
        - base/cs/database/index.md
      - 操作系统:
        - base/cs/operating-system/index.md
        - base/cs/operating-system/intro.md
        - base/cs/operating-system/concurrent.md
        - base/cs/operating-system/virtualization.md
        - base/cs/operating-system/persistence.md
      - 计算机组成:
        - base/cs/computer-organization/index.md
        - base/cs/computer-organization/cpu.md
        - base/cs/computer-organization/memory.md
        - base/cs/computer-organization/device.md
      - 计算机网络:
        - base/cs/computer-network/index.md
        - base/cs/computer-network/application-layer.md
        - base/cs/computer-network/transport-layer.md
        - base/cs/computer-network/network-layer.md
        - base/cs/computer-network/data-link-layer.md
        - base/cs/computer-network/physical-layer.md
    - 数学基础:
      - 高等数学:
        - base/math/advanced-math/index.md
        - base/math/advanced-math/differentiation.md
        - base/math/advanced-math/integration.md
      - 线性代数:
        - base/math/linear-algebra/index.md
      - 概率统计:
        - base/math/probability-and-statistics/index.md
        - base/math/probability-and-statistics/prob.md
        - base/math/probability-and-statistics/stat.md
      - 最优化方法:
        - base/math/optimization-method/index.md
        - base/math/optimization-method/linear-search.md
        - base/math/optimization-method/unconstraint-optimization.md
        - base/math/optimization-method/constraint-optimization.md
    - 其他:
      - 大学物理:
        - base/others/college-physics/index.md
      - 英语语法:
        - base/others/english-grammar/index.md
        - base/others/english-grammar/word-property.md
        - base/others/english-grammar/sentence-ingredient.md
        - base/others/english-grammar/sentence-type.md
  - 炼丹:
    - data-science/index.md
    - 数据科学常用第三方库:
      - data-science/pkgs/numpy.md
      - data-science/pkgs/pandas.md
      - data-science/pkgs/matplotlib.md
      - data-science/pkgs/torch.md
    - 传统机器学习算法:
      - data-science/shallow-model/linear.md
    - 现代深度学习模型:
      - data-science/deep-model/cpu2gpu.md
      - data-science/deep-model/gpu2gpus.md
      - data-science/deep-model/fnn.md
  - 算法:
    - ds-and-algo/index.md
    - ds-and-algo/templates.md
    - ds-and-algo/templates-py.md
    - 专题解析:
      - ds-and-algo/topic/index.md
      - ds-and-algo/topic/base.md
      - ds-and-algo/topic/ds.md
      - ds-and-algo/topic/dp.md
      - ds-and-algo/topic/geometry.md
      - ds-and-algo/topic/string.md
      - ds-and-algo/topic/graph.md
      - ds-and-algo/topic/math.md
      - ds-and-algo/topic/others.md
    - 蓝桥杯备赛指南:
      - ds-and-algo/lan-qiao-cup/index.md
      - ds-and-algo/lan-qiao-cup/16th-python-a.md
      - ds-and-algo/lan-qiao-cup/15th-python-a.md
      - ds-and-algo/lan-qiao-cup/14th-python-a.md
      - ds-and-algo/lan-qiao-cup/13th-python-a.md
    - 睿抗备赛指南:
      - ds-and-algo/raicom-caip/index.md
  - 前端:
    - front-end/index.md
    - front-end/html-basic.md
    - front-end/css-basic.md
    - front-end/yaml-basic.md
    - JavaScript:
      - front-end/javascript/javascript-basic.md
      - front-end/javascript/javascript-advanced.md
    - Hexo:
      - front-end/hexo/build-your-own-website-with-hexo.md
      - front-end/hexo/hexo-deployment.md
      - front-end/hexo/hexo-enhancement.md
  - 后端:
    - back-end/index.md
    - C++ 标准库:
      - back-end/cpp-std/index.md
      - back-end/cpp-std/base.md
      - back-end/cpp-std/io.md
      - back-end/cpp-std/container.md
      - back-end/cpp-std/algo.md
      - back-end/cpp-std/string.md
      - back-end/cpp-std/utils.md
      - back-end/cpp-std/pointer.md
      - back-end/cpp-std/concurrent.md
      - back-end/cpp-std/datetime.md
      - back-end/cpp-std/math.md
      - back-end/cpp-std/exception.md
    - Python 标准库:
      - back-end/py-std/index.md
      - back-end/py-std/setup.md
      - back-end/py-std/base.md
    - 网络编程:
      - back-end/web/flask.md
      - back-end/web/crow.md
    - MySQL:
      - back-end/mysql/mysql-basic.md
      - back-end/mysql/mysql-problem-solve.md
    - openGauss:
      - back-end/opengauss/opengauss-setup.md
      - back-end/opengauss/opengauss-basic.md
  - 运维:
    - operation/index.md
    - operation/gnu-linux-basic.md
    - operation/gnu-linux-advanced.md
    - Nginx:
      - operation/nginx/nginx-commands.md
      - operation/nginx/nginx-setup.md
      - operation/nginx/nginx-examples.md
  - 工具:
    - dev-tools/index.md
    - dev-tools/jetbrains-license.md
    - dev-tools/download.md
    - 软件配置:
      - dev-tools/setup/windows-setup.md
      - dev-tools/setup/devcpp-setup.md
      - dev-tools/setup/idle-setup.md
      - dev-tools/setup/clion-setup.md
    - Git:
      - dev-tools/git/git-commands.md
      - dev-tools/git/git-pull-request.md
      - dev-tools/git/git-self-define-command.md
      - dev-tools/git/git-branch-conflict.md
      - dev-tools/git/git-tips.md
  - 博客: https://blog.dwj601.cn/
