# 站点配置
site_name: Open Wiki Community
site_url: https://wiki.dwj601.cn/
repo_url: https://github.com/Explorer-Dong/explorer-dong.github.io
repo_name: explorer-dong.github.io
edit_uri: edit/main/docs/


# 主题配置
theme:
  name: material
  language: zh
  custom_dir: overrides
  # 图标
  logo: https://dwj-oss.oss-cn-nanjing.aliyuncs.com/web-imgs/img-static/wiki-16px.svg
  favicon: https://dwj-oss.oss-cn-nanjing.aliyuncs.com/web-imgs/img-static/wiki-16px.svg
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  # 颜色
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到亮色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到自动模式
  features:
    # - header.autohide              # 自动隐藏页面头部
    - navigation.tabs                # 顶部一级分类导航栏
    # - navigation.tabs.sticky         # 固定顶部一级分类导航栏
    - navigation.sections          # 分类页小标题
    # - navigation.expand            # 分类页默认展开
    - navigation.indexes           # 不显示分类索引首页
    - navigation.top               # 顶部导航栏
    - navigation.footer            # 页脚
    - content.code.copy            # 代码块复制按钮
    - content.code.select          # 代码块选中行
    - content.tooltips             # 内容悬浮提示
    - content.action.edit          # 编辑源文件按钮
    - content.action.view          # 查看源文件按钮
    - search.highlight             # 搜索结果高亮
    - search.share                 # 社交分享按钮
    - search.suggest               # 搜索建议
    - toc.follow                   # 目录跟随滚动（需要 markdown_extensions.toc.permalink 开启）
    - announce.dismiss             # 支持手动关闭公告


# md 语法扩展
markdown_extensions:
  # 并列嵌套（需要和 superfences 一起使用）
  - pymdownx.tabbed:
      alternate_style: true
  # 悬浮提示
  - abbr
  - attr_list
  - pymdownx.snippets
  # 折叠块
  - pymdownx.details
  # 内容框
  - admonition
  # 脚注
  - footnotes
  # 目录
  - toc:
      permalink: true             # 显示标题链接
      toc_depth: 4                # 显示目录深度
      title: 目录                 # 目录标题
      permalink_title: 页面定位   # 链接标题
      slugify: !!python/name:pymdownx.slugs.uslugify  # 禁止重写标题，借鉴 oi-wiki 的配置
  # 数学公式
  - pymdownx.arithmatex:
      generic: true
  # 表情符号
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # 图表标题
  - pymdownx.blocks.caption:
      types:
        - caption
        # 自动编号
        - name: fc            # figure caption
          prefix: '图 {}. '
        - name: tc            # table caption
          prefix: '表 {}. '
  # 代码高亮
  - pymdownx.highlight:
      # auto_title: true           # 自动标题
      use_pygments: true         # 第三方库增强
      pygments_lang_class: true  # 语言定制化高亮
      linenums: true             # 显示行号
      anchor_linenums: true      # 行号锚点
      line_spans: __span         # 行号容器（移动端适配）
  # 任务列表
  - pymdownx.tasklist:
      custom_checkbox: true


# 注入
extra_javascript:
  # KaTeX
  - asserts/javascripts/katex.js
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.js
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/contrib/auto-render.min.js
  # mermaid
  - https://dwj-oss.oss-cn-nanjing.aliyuncs.com/cdn-js/mermaid/mermaid.min.js
  # 外链跳转
  - asserts/javascripts/link_blank.js
  # 百度统计
  - asserts/javascripts/baidu_tongji.js
  # 聊天机器人
  - asserts/javascripts/robot.js
extra_css:
  # KaTeX
  - https://registry.npmmirror.com/katex/0.16.21/files/dist/katex.min.css
  # 自定义样式
  - asserts/stylesheets/extra.css


# 插件配置
plugins:
  # 搜索功能
  - search:
      lang: zh
  # 显示文章创建和修改时间
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  # 显示文章作者（头像与 GitHub Profile 链接）
  - git-committers:
      repository: Explorer-Dong/explorer-dong.github.io
      branch: main
  # 图片可点击放大
  - glightbox:
      auto_caption: true
  # meta 配置
  - meta


draft_docs: _*.md

# 页面导航
nav:
  - index.md
  - 基础:
    - base/index.md
    - 人工智能基础:
      - Python 高级应用:
        - base/python-application/index.md
      - 数字图像处理:
        - base/digital-image-processing/index.md
      - 数字信号处理:
        - base/digital-signal-processing/index.md
      - 机器学习:
        - base/machine-learning/index.md
        - base/machine-learning/data.md
        - 模型:
          - base/machine-learning/model/index.md
          - base/machine-learning/model/linear-model.md
          - base/machine-learning/model/decision-tree-model.md
          - base/machine-learning/model/bayes-model.md
          - base/machine-learning/model/probability-graph-model.md
          - base/machine-learning/model/ensemble-learning.md
          - base/machine-learning/model/lazy-learning.md
          - base/machine-learning/model/cluster-learning.md
          - base/machine-learning/model/semi-supervised-learning.md
        - base/machine-learning/eval.md
      - 深度学习:
        - base/deep-learning/index.md
      - 数据挖掘:
        - base/data-mining/index.md
        - base/data-mining/data-preprocess.md
        - base/data-mining/association-analysis.md
        - base/data-mining/anomaly-detection.md
      - 自然语言处理:
        - base/natural-language-processing/index.md
        - base/natural-language-processing/model.md
        - base/natural-language-processing/task.md
      - 计算机视觉:
        - base/computer-vision/index.md
        - base/computer-vision/image-classification.md
        - base/computer-vision/semantic-segmentation.md
        - base/computer-vision/object-detection.md
      - 智慧教育:
        - base/intelligent-education/index.md
    - 计算机基础:
      - 面向对象程序设计:
        - base/object-oriented-programming/index.md
      - 数字逻辑电路:
        - base/digital-logic-circuit/index.md
      - 计算机系统基础:
        - base/computer-system-basic/index.md
      - 数据库:
        - base/database/index.md
      - 操作系统:
        - base/operating-system/index.md
        - base/operating-system/intro.md
        - base/operating-system/concurrent.md
        - base/operating-system/virtualization.md
        - base/operating-system/persistence.md
      - 计算机组成:
        - base/computer-organization/index.md
        - base/computer-organization/cpu.md
        - base/computer-organization/memory.md
        - base/computer-organization/device.md
      - 计算机网络:
        - base/computer-network/index.md
        - base/computer-network/application-layer.md
        - base/computer-network/transport-layer.md
        - base/computer-network/network-layer.md
        - base/computer-network/data-link-layer.md
        - base/computer-network/physical-layer.md
    - 数理基础:
      - 大学物理:
        - base/college-physics/index.md
      - 高等数学:
        - base/advanced-math/index.md
        - base/advanced-math/differentiation.md
        - base/advanced-math/integration.md
      - 线性代数:
        - base/linear-algebra/index.md
      - 概率论:
        - base/probability-and-statistics/index.md
      - 最优化方法:
        - base/optimization-method/index.md
        - base/optimization-method/intro.md
        - base/optimization-method/linear-search.md
        - base/optimization-method/unconstraint-optimization.md
        - base/optimization-method/constraint-optimization.md
  - 炼丹:
    - data-science/index.md
    - data-science/numpy-basic.md
    - data-science/pandas-basic.md
    - data-science/matplotlib-basic.md
  - 算法:
    - ds-and-algo/index.md
    - ds-and-algo/templates.md
    - ds-and-algo/templates-py.md
    - 理论剖析:
      - ds-and-algo/theory/index.md
      - ds-and-algo/theory/base.md
      - ds-and-algo/theory/ds.md
      - ds-and-algo/theory/dp.md
      - ds-and-algo/theory/string.md
      - ds-and-algo/theory/geometry.md
      - ds-and-algo/theory/graph.md
      - ds-and-algo/theory/game.md
      - ds-and-algo/theory/math.md
    - 配套习题:
      - ds-and-algo/examples/index.md
      - ds-and-algo/examples/examples-basic-algo.md
      - ds-and-algo/examples/examples-advanced-algo.md
      - ds-and-algo/examples/examples-ds.md
    - 蓝桥杯备赛指南:
      - ds-and-algo/lan-qiao-cup/index.md
      - ds-and-algo/lan-qiao-cup/14th-python-a.md
      - ds-and-algo/lan-qiao-cup/15th-python-a.md
  - 前端:
    - front-end/index.md
    - front-end/html-basic.md
    - front-end/css-basic.md
    - JavaScript:
      - front-end/javascript/javascript-basic.md
    - Hexo:
      - front-end/hexo/build-your-own-website-with-hexo.md
      - front-end/hexo/hexo-deployment.md
      - front-end/hexo/hexo-enhancement.md
  - 后端:
    - back-end/index.md
    - C++:
      - back-end/cplusplus/index.md
      - back-end/cplusplus/cpp-basic.md
      - back-end/cplusplus/cpp-advanced.md
    - Python:
      - back-end/python/python-setup.md
      - back-end/python/python-basic.md
      - Flask:
        - back-end/python/flask/deploy-flask.md
    - 数据库:
      - back-end/database/database-basic.md
      - MySQL:
        - back-end/database/mysql/mysql-basic.md
        - back-end/database/mysql/solve-mysql-problems.md
      - openGauss:
        - back-end/database/opengauss/opengauss-basic.md
        - back-end/database/opengauss/opengauss-remote-connect.md
        - back-end/database/opengauss/opengauss-import-data.md
  - 运维:
    - operation/index.md
    - Nginx:
      - operation/nginx/nginx-basic.md
      - operation/nginx/nginx-command.md
      - operation/nginx/solve-nginx-reload-error.md
      - operation/nginx/whereis-nginx.md
    - 安全:
      - operation/safe/solve-server-invade.md
    - CLI:
      - operation/shell/shell-basic.md
      - operation/shell/solve-shell-problems.md
      - operation/shell/ubuntu-guide.md
  - 工具:
    - dev-tools/index.md
    - dev-tools/windows-setup.md
    - dev-tools/jetbrains-license.md
    - dev-tools/devcpp-lqb-config.md
    - dev-tools/idle-lqb-config.md
    - CLion:
      - dev-tools/clion/clion-config.md
      - dev-tools/clion/solve-clion-problems.md
    - Git:
      - dev-tools/git/git-basic.md
      - dev-tools/git/git-pull-request.md
      - dev-tools/git/git-self-define-command.md
      - dev-tools/git/solve-git-problems.md
  - 博客: https://blog.dwj601.cn/


# 额外配置
extra:
  # 谷歌分析
  analytics:
    provider: google
    property: G-56NDVC0D5B
  # 文章状态定义
  status:
    new: 最近新增
    deprecated: 即将废弃
  # 页面底部社交链接
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Explorer-Dong
      name: GitHub
    - icon: fontawesome/solid/c
      link: https://blog.csdn.net/qq_73408594
      name: CSDN


# 页脚 Copyright
copyright: Copyright &copy; 2024 - 2025 Wenjie
