name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      # 相当于 git clone 到服务器
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # 在服务器上安装 Node.js 环境
      - name: Setup Node.js environment 📦
        uses: actions/setup-node@v2
        with:
          node-version: 20.11.1

      # 安装依赖
      - name: Install Dependencies 🔨
        run: npm install

      # 构建静态页面并部署
      - name: Build and Deploy 🚀
        env:
          token: ${{ secrets.HEXO_DEPLOY }}
        run: |
          git config --global user.email "explorer-dong@foxmail.com"
          git config --global user.name "Mr_Dwj"
          npm run build
          npm run deploy
